# Site settings
title:       Kevin Cashman
email:       kevinjcash@gmail.com
author:      Kevin Cashman
description: "A blog written by Kevin Cashman"
baseurl:     ""
url:         "http://kevinjcash.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons:  false
github_username:    "kevinjcash"
stackoverflow_id:
twitter_username:   "KevinJCashman"
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
